### ISSUE TITLE
FoxCore Wand Data causes Exception

### ISSUE THREAD

**Issue by Xaymar** [FoxDenStudio/FoxCore#15]
I've been running into a repeated problem with FoxCore/FoxGuard lately, namely that it freezes the main server thread after about ~12-18 hours server runtime. The Main thread will be stuck at 100% core usage, with two side threads being at 100% and 80% respectively. This behavior goes away if FoxCore/FoxGuard is removed, but that is not really the scope of this issue - I'm still trying to figure out why it happens, so nothing clear on that yet.

This issue is something that just now happened: I can no longer join after getting that above behavior. The FoxCore Wand in my inventory is causing an exception, so I'm kicked off the server. This happened after warping myself with Nucleus `/rtp` and getting the above explained FC/FG freeze.

### Versions:
* Minecraft: 1.12.2
* Forge: 14.23.5.2810
* SpongeForge: 2768-7.1.6
* FoxCore: 0.22.0 Beta 258 Server
* FoxGuard: 0.22.0 Beta 450 Server
* LuckPerms Sponge: 4.3.87

### Console Log:
```
[13:38:29] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /********
net.minecraft.util.ReportedException: Loading entity NBT
        at net.minecraft.entity.Entity.func_70020_e(Entity.java:1878) ~[vg.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75752_b(SaveHandler.java:224) ~[bfb.class:?]
        at net.minecraft.server.management.PlayerList.func_72380_a(PlayerList.java:324) ~[pl.class:?]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1482) ~[pl.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255) ~[NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) ~[NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.foxdenstudio.sponge.foxcore.plugin.wand.data.WandKeys
        at net.foxdenstudio.sponge.foxcore.plugin.wand.data.WandData.registerGettersAndSetters(WandData.java:92) ~[WandData.class:?]
        at net.foxdenstudio.sponge.foxcore.plugin.wand.data.WandData.<init>(WandData.java:63) ~[WandData.class:?]
        at net.foxdenstudio.sponge.foxcore.plugin.wand.data.WandData.<init>(WandData.java:67) ~[WandData.class:?]
        at net.foxdenstudio.sponge.foxcore.plugin.wand.data.WandDataBuilder.create(WandDataBuilder.java:48) ~[WandDataBuilder.class:?]
        at net.foxdenstudio.sponge.foxcore.plugin.wand.data.WandDataBuilder.buildContent(WandDataBuilder.java:60) ~[WandDataBuilder.class:?]
        at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:87) ~[AbstractDataBuilder.class:1.12.2-2768-7.1.6-RC3560]
        at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulator$11(DataUtil.java:239) ~[DataUtil.class:1.12.2-2768-7.1.6-RC3560]
        at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_201]
        at org.spongepowered.common.data.util.DataUtil.deserializeManipulator(DataUtil.java:239) ~[DataUtil.class:1.12.2-2768-7.1.6-RC3560]
        at org.spongepowered.common.data.util.DataUtil.tryDeserializeManipulator(DataUtil.java:225) ~[DataUtil.class:1.12.2-2768-7.1.6-RC3560]
        at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulatorList$10(DataUtil.java:206) ~[DataUtil.class:1.12.2-2768-7.1.6-RC3560]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_201]
        at org.spongepowered.common.data.util.DataUtil.deserializeManipulatorList(DataUtil.java:206) ~[DataUtil.class:1.12.2-2768-7.1.6-RC3560]
        at net.minecraft.item.ItemStack.readFromNbt(ItemStack.java:2629) ~[aip.class:?]
        at net.minecraft.item.ItemStack.handler$onRead$zif000(ItemStack.java:2461) ~[aip.class:?]
        at net.minecraft.item.ItemStack.<init>(ItemStack.java:139) ~[aip.class:?]
        at net.minecraft.entity.player.InventoryPlayer.func_70443_b(InventoryPlayer.java:639) ~[aec.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70037_a(EntityPlayer.java:874) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70037_a(EntityPlayerMP.java:195) ~[oq.class:?]
        at net.minecraft.entity.Entity.func_70020_e(Entity.java:1866) ~[vg.class:?]
        ... 13 more
```

**Comment by ghost** [comment]
O.o

I'll make sure Fox sees this... Depending on how his university is going, he may have an answer shortly.

**Comment by ghost** [comment]
Hi @Xaymar ,

Can you please upload the debug and latest log files (and/or crash file if the exist). 

If you would like, you can share a link directly with me on discord, or you can share it here: 
`Snowie (D4rk)#1374`

This is not an issue we have ever seen before, and looks like Java just...

Thanks!

**Comment by ghost** [comment]
Actually, we think we might have found the issue, standby. I will update this when we have the solution. In the meantime, logs would still be helpful.

**Comment by Xaymar** [comment]
[Temp.zip](https://github.com/FoxDenStudio/FoxCore-Sponge/files/2845028/Temp.zip)

Zip contains log and debug file from that day. I have been unable to get this to happen again yet (but I still experience the freezes, which seem to originate from saving files).

**Comment by Xaymar** [comment]
Closing this to get rid of entries in my open issues list.
